## Basic Configuration

baseurl = "http://harsain.com"
title = "Harsain Kapoor"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "hskoder"
enableRobotsTXT = true


## Site Settings
## Controls the navigation
[menu]
[[menu.header]]
name = "post"
weight = 0
url = "post"
[[menu.header]]
name = "about"
weight = 1
url = "about"

[params]
GithubID = "harsain"
TwitterID = "harsain"
LinkedInID = "harsain"
SpotifyID = "harsain"
Name = "Harsain Kapoor"
HeaderUsername = "welcome"
HeaderHostname = "harsain.com"
Email = "hskoder@gmail.com"
About = "Hi I'm Hugo and this is my website. I am a developer, writer and family man. I like developing websites using Hugo, sports, nature, photography and travel. On this websites you can expect my projects and blog posts about everything I love. Enjoy!"
ProfilePicture = "/img/avatar.jpg"
Favicon = "/favicon.ico"
